apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: default
spec:
  containers:
    - name: mysql-client
      image: mysql:8
      command: ["sleep", "3600"]
      env:
        - name: MYSQL_HOST
          value: "dev-db.clm46go82ob4.ap-southeast-1.rds.amazonaws.com"  # Replace with your actual MySQL RDS endpoint
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: password
      tty: true
      stdin: true
  restartPolicy: Never

