apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-db-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: auth-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: rds/dev/db_credentials
        property: username
    - secretKey: password
      remoteRef:
        key: rds/dev/db_credentials
        property: password
