apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  type: NodePort
  ports:
    - name: http     # required field
      port: 9000
      targetPort: 9000
      nodePort: 32000
  selector:
    app: sonarqube
